### PR TITLE
Add the possibility to listen multiples twitch channels properly

### PR DESCRIPTION
**Pull request by jpiazzal**
I took the opportunity to make a little refacto of the code ;)
Do not hesitate if you have any questions.

### CODE REVIEW

**Comment by jpiazzal** [comment]
don't forget to add topic "hacktoberfest" to you repository to be sure to participate to hacktoberfest ;)

**Comment by samyakbambole** [comment]
> don't forget to add topic "hacktoberfest" to you repository to be sure to participate to hacktoberfest ;)

Done! 😀👍

**Comment by samyakbambole** [comment]
Ohh This is Actually a good PR! I will be glad to merge this PR.

**Comment by samyakbambole** [comment]
@jpiazzal make sure to check #7 See if you can help!

**Pull request merged**
