### PR TITLE
Feature/manage channels ui

### PR DESCRIPTION
**Pull request by nicolashacala**
Managing channel thanks to the UI.

### CODE REVIEW

**Comment by samyakbambole** [comment]
image

I am recieving this error in the Actions @nicolashacala

**Comment by samyakbambole** [comment]
This was a good PR! this Really improved the app!

**Comment by nicolashacala** [comment]
I am not sure how those actions work, but prior to my PR, to run the app we had to run: "npm start 'CHANNEL'" but those actions files run: "npm start" which should actually exit the app.
With my modifications, after 'npm start', the app actually keeps running as the 'CHANNEL' parameter is no longer needed.
So I would think those checks need to be modified but as I said I don't know how those works so I might be wrong.

**Comment by nicolashacala** [comment]
Actually from what I read and from what my colleagues told me, I am not sure your action file should run the app. One of my colleague mentioned that if you really want to run it to see if it works, you should set a timer and validate the check if the app ran during this timer.

**Pull request merged**
