### PR TITLE
Feature/messages display

### PR DESCRIPTION
**Pull request by nicolashacala**

### CODE REVIEW

**Comment by samyakbambole** [comment]
I would like to check and review all the code and then ill try to merge this PR! But there are Conflicts in this branch.

**Comment by nicolashacala** [comment]
Thanks for your reply, I resolved the conflicts and updated my PR.

**Comment by samyakbambole** [comment]
> Thanks for your reply, I resolved the conflicts and updated my PR.

Can You please tell me What these updates do?

**Comment by nicolashacala** [comment]
Color of the logs varies depending on users color, a '[MOD]' in front of username if user is MOD

**Pull request closed without merging**
